name: git-ddiff
version: '1.0.0'
summary: https://github.com/cookiengineer/git-ddiff
description: |
  git ddiff - a better git diff for humans with lack of memory
grade: devel
confinement: devmode
apps:
  git-ddiff:
    command: git-ddiff
parts:
  git-ddiff:
    source: https://github.com/cookiengineer/git-ddiff.git
    plugin: nodejs
    node-engine: '7.10.1'
