name: backslide
version: '1.0.2'
summary: https://github.com/sinedied/backslide
description: |
  CLI tool for making HTML presentations with Remark.js using Markdown https://sinedied.github.io/backslide
grade: stable
confinement: strict
apps:
  backslide:
    command: bs
    plugs: [home,network,network-bind]
    aliases: [bs]
parts:
  backslide:
    source: https://github.com/sinedied/backslide.git
    plugin: nodejs
