name: backslide
version: '1.0.5'
summary: https://github.com/sinedied/backslide
description: |
  CLI tool for making HTML presentations with Remark.js using Markdown https://sinedied.github.io/backslide
grade: stable
confinement: classic
apps:
  backslide:
    command: bs
parts:
  backslide:
    source: https://github.com/sinedied/backslide.git
    plugin: nodejs
